const ADD_TO_CART = 'ADD_TO_CART';
const INCREASE = 'INCREASE';
const DECREASE = 'DECREASE';
const CLEAR_CART = 'CLEAR_CART';
const PURCHASE = 'PURCHASE';

export { ADD_TO_CART, INCREASE, DECREASE, CLEAR_CART, PURCHASE };
